# Recommened editor for this file: https://github.com/Microsoft/azure-pipelines-vscode

schedules:
  # run weekly to keep cache fresh
  - cron: "0 0 * * 0"
    branches:
      include: 
      - master
    always: true

variables:
  CHANNEL: stable
  CACHE_SALT: 1
  RUSTCACHE_ROOT: $(Build.SourcesDirectory)/target
  CARGO_DEPENDENCIES_FILE: $(Pipeline.Workspace)/Cargo.dependencies
  CARGO_HOME: $(RUSTCACHE_ROOT)/rustcache/.cargo
  RUSTUP_HOME: $(RUSTCACHE_ROOT)/rustcache/.rustup
  SCCACHE_DIR: $(RUSTCACHE_ROOT)/rustcache/sccache
  SCCACHE_CACHE_SIZE: 1G
  CACHE_KEY_BASE: '"CACHE_SALT=$(CACHE_SALT)-$(VM_IMAGE)-$(CHANNEL)-$(TOOLS_TARGET)-$(TARGET)-ENABLE_SCCACHE=$(ENABLE_SCCACHE)-AZP_CACHING_CONTENT_FORMAT=$(AZP_CACHING_CONTENT_FORMAT)"'
  TOOLS_TARGET: $(TARGET)
  POOL_NAME: ''
  VM_IMAGE: ''
  ENABLE_SCCACHE: 0
  System.Debug: true

jobs:
  - job: cached
    pool:
      name: $(POOL_NAME)
    strategy:
      matrix:
        vs2019-msvc-dataport:
          TARGET: x86_64-pc-windows-msvc
          POOL_NAME: dataport
          ENABLE_DATAPORT: 1

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          source: 'specific'
          artifactName: 'cache'
          path: '$(Build.SourcesDirectory)/out1'
          project: '$(system.teamProjectId)'
          pipeline: 298
          runVersion: 'specific'
          runId: 17076